development: &development
  adapter: postgresql
  database: jadecrm
  username: postgres
  password: admin  # If you've set a password for postgres
  host: localhost
  port: 5432
  schema_search_path: public
  min_messages: warning

test:
  <<: *development
  database: fat_free_crm_test

production:
  adapter: postgresql
  host: openweb-db.postgres.database.azure.com
  database: jadecrm
  username: adminjade
  password: "!JadeAdvisory@2025#"
  port: 5432
  sslmode: require
  schema_search_path: public
  min_messages: warning

staging:
  <<: *development
  database: fat_free_crm_staging
